### ISSUE TITLE
Duplicate `[CompilerGenerated]` attribute emitted on field-like event backing fields (CS0579)

### ISSUE THREAD

**Issue by SBvn-dev** [icsharpcode/ILSpy#3716]
### Steps to reproduce

When decompiling a class that contains a C#-style field-like event with an
**explicit** `add` / `remove` accessor pair (the kind the compiler emits when
the source uses `Interlocked.CompareExchange` for thread-safe subscribe), the
private backing field for the event is emitted with two consecutive
`[CompilerGenerated]` attributes, which fails to compile with `CS0579`.

The shape that triggers it: a type with two unrelated field-like events whose
backing fields are typed as `EventHandler` and accessed inside the explicit
add/remove via the `Interlocked.CompareExchange(ref _backingField, ...)`
idiom.

Minimal repro source (compile with C# 7.3, then re-decompile):

```csharp
using System;
using System.Threading;

public class Repro
{
    public event EventHandler Changed;
    public event EventHandler LengthChanged;

    public void RaiseChanged() => Changed?.Invoke(this, EventArgs.Empty);
    public void RaiseLength()  => LengthChanged?.Invoke(this, EventArgs.Empty);
}
```

Compile this against .NET Framework 4.8, then run:

```
ilspycmd Repro.dll -p -lv CSharp7_3 -o ./out
```

### Erroneous output (`Repro.cs`)

```csharp
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Threading;

public class Repro
{
    [CompilerGenerated]
    [CompilerGenerated]                                  // <-- DUPLICATE
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private EventHandler Changed;

    [CompilerGenerated]
    [CompilerGenerated]                                  // <-- DUPLICATE
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private EventHandler LengthChanged;

    // ... add/remove pair using Interlocked.CompareExchange ...
}
```

Roslyn rejects this with two errors:

```
Repro.cs(8,3): error CS0579: Duplicate 'CompilerGenerated' attribute
Repro.cs(13,3): error CS0579: Duplicate 'CompilerGenerated' attribute
```

### Expected output

A single `[CompilerGenerated]` per backing field, matching what the compiler
originally emitted.

### Notes

The IL contains the attribute exactly once on each backing field row — this
is purely a duplication in the decompiler's emit path. The attribute appears
to be added by both the generic field-attribute path and the
"this looks like a field-like event backing field" reconstruction path
without checking whether the other already added it.

Possibly related (closed): #3575 — "Uses of compiler-generated events getting
swapped with non-generated events of same type" — the fix landed in
commit 7b03606402 (Oct 2025) but does not cover this specific shape (two
unrelated events on the same type, each with their own backing field, both
using the explicit `Interlocked.CompareExchange` add/remove pattern).

### Details

* Product in use: ilspycmd
* Version in use: 10.0.0.8330 (latest stable as of 2026-04-13)
* Target assembly is a .NET Framework 4.8 class library / WinForms application

**Comment by siegfriedpammer** [comment]
Thanks for the report. Unfortunately, I cannot reproduce this, and several details in the report don't match how the compiler and the decompiler actually behave:

- Compiling the repro source exactly as described (net48, `-langversion:7.3`, Release and Debug) and decompiling with `ilspycmd 10.0.0.8330` using the exact command given (`-p -lv CSharp7_3 -o`) produces a clean field-like event declaration for both events — no backing fields, no attributes, and the output compiles. The same is true with current master.
- The claimed IL shape is wrong: csc emits exactly one `[CompilerGenerated]` on a field-like event's backing field and no `[DebuggerBrowsable]` (that attribute is part of the auto-*property* pattern, not events).
- The claimed output (a `private EventHandler Changed;` field next to an event of the same name) would be rejected by the compiler with CS0102 before any CS0579 could occur; ILSpy does not produce this shape for the given input.

A duplicated attribute in the output would require the attribute to be duplicated in the metadata itself (which some obfuscators/mergers do), and that contradicts the report's claim that the IL contains it once.

I'm closing this as not reproducible. If you hit this on a real assembly, please attach the binary (or a trimmed-down copy that still shows the problem) and the exact ilspycmd version/command, and we'll gladly take another look.

*This analysis was performed and written by an AI agent (Claude Code) operated by @siegfriedpammer.*
